Hudson core now bundles Rhino, which breaks java.net tasks with errors like this:
FATAL: org/mozilla/javascript/NotAFunctionException
java.lang.NoClassDefFoundError: org/mozilla/javascript/NotAFunctionException
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2427)
	at java.lang.Class.getDeclaredMethods(Class.java:1791)
	at org.mozilla.javascript.FunctionObject.getMethodList(FunctionObject.java:315)
	at org.mozilla.javascript.ScriptableObject.buildClassCtor(ScriptableObject.java:1014)
	at org.mozilla.javascript.ScriptableObject.defineClass(ScriptableObject.java:998)
	at org.mozilla.javascript.ScriptableObject.defineClass(ScriptableObject.java:931)
	at com.meterware.httpunit.javascript.JavaScript.initHTMLObjects(JavaScript.java:86)
	at com.meterware.httpunit.javascript.JavaScript.run(JavaScript.java:77)
	at com.meterware.httpunit.javascript.JavaScriptEngineFactory.associate(JavaScriptEngineFactory.java:46)
	at com.meterware.httpunit.FrameHolder.<init>(FrameHolder.java:44)
	at com.meterware.httpunit.WebWindow.<init>(WebWindow.java:218)
	at com.meterware.httpunit.WebClient.<init>(WebClient.java:50)
	at com.meterware.httpunit.WebConversation.<init>(WebConversation.java:46)
	at org.kohsuke.jnt.JavaNet.<init>(JavaNet.java:47)
	at org.kohsuke.jnt.JavaNet.connect(JavaNet.java:130)
	at org.kohsuke.jnt.JavaNet.connect(JavaNet.java:112)
	at hudson.plugins.javanet_uploader.JNUploaderPublisher.perform(JNUploaderPublisher.java:62)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:56)
	at hudson.model.AbstractBuild$AbstractRunner.performAllBuildStep(AbstractBuild.java:372)
	at hudson.model.AbstractBuild$AbstractRunner.performAllBuildStep(AbstractBuild.java:360)
	at hudson.model.Build$RunnerImpl.post2(Build.java:183)
	at hudson.model.AbstractBuild$AbstractRunner.post(AbstractBuild.java:345)
	at hudson.model.Run.run(Run.java:947)
	at hudson.model.Build.run(Build.java:112)
	at hudson.model.ResourceController.execute(ResourceController.java:93)

So remove JavaScript support much earlier.



git-svn-id: https://hudson.dev.java.net/svn/hudson/trunk/hudson/plugins@18102 71c3de6d-444a-0410-be80-ed276b4c234a